from datetime import datetime
import json
from dotenv import load_dotenv
from copy import deepcopy
from memory import MemoryClient, Memory
from sources import InputSource, InputSourceHub, OutputSource, OutputSourceHub, GradioUI
from prompts import system_prompts
from helpers import count
load_dotenv(override=True)


class Context:
    """
    Contains all the contexts for an agent and their related methods for the agent and input sources to interact with.

    Context:
    - Messages
    - Memory
    - Custom contexts generated by tools, subagents,...

    Input sources:
    - User chat messages fron the chat UI
    - Tool calls, subagents
    """

    # persona_name: str
    # persona: str
    # """
    # Persona configs, loaded from personas.json:
    # persona_name: Name of the persona
    # persona: persona description
    # """

    messages = []
    """History of all messages including tool calls and thoughts"""


    # memory_client: MemoryClient
    # memories: Memory
    # """Memory objects to retrieve memories"""

    input_sources: InputSourceHub
    """Input sources for the agent to fetch input from"""

    output_sources: OutputSourceHub
    """Output sources for the agent to send output to"""

    reasoning_prompt: str
    """The latest user message sent to the reasoning_agent. Used to remind the agent in a single long run"""

    system_prompt: str
    """System prompt for the agent"""
    keywords: dict
    """Special keywords in prompts that need care"""

    max_tokens: dict[str, int]
    """
    The maximum number of tokens in each context sections.
    Each pair consists of section name (messages, memories,...) and max tokens values
    For messages, each summarization will consume half of the limit
    """

    max_files: dict[str, int]
    """
    The maximum number of files in each context sections.
    Each pair consists of section name (messages, memories,...) and max files values
    """



    def __init__(self, input_sources: dict[str, InputSource] = {}, output_sources: dict[str, OutputSource] = {}, agent_type: str = "assistant", max_tokens: int = 5000, max_files: int = 5) -> None:
        """
        Init the context

        Get the system prompt from prompts module based on the agent type.
        Init messages (the n latest messages), memory,...

        Parameters:
            input_sources: a dict mapping the source names in str to the InputSource objects
            output_sources: a dict mapping the source names in str to the OutputSource objects
            agent_type: the type of the agent using this Context object
            max_tokens: the maximum number of tokens for the context. Divided into multiple sections in the method
        """
        
        # Initialize input sources
        self.input_sources = InputSourceHub(sources=input_sources)
        self.input_sources.connect_all()

        # Initialize output sources
        self.output_sources = OutputSourceHub(sources=output_sources) 
        self.output_sources.connect_all() 

        
        # FIXME: Use SQLClient to fetch the latest messages from a sql database
        self.messages = [{
            'role': 'user',
            'content': f'System starts. Now is {datetime.now().astimezone().isoformat()}'
            }]
        
        self.simple_conversation_history = ''

        self.reasoning_prompt = ''

        # Get the system prompt from prompts module
        self.system_prompt = system_prompts[agent_type]

        self.keywords = {
            # Keyword to indicate there's no new input
            'no_input': '[no input]'
        }

        # Init the context length limit
        # FIXME: add more sections later
        self.max_tokens = {
            "messages": max_tokens
        }
        self.max_files = {
            "messages": max_files
        }


    def fetch_messages(self) -> tuple:
        """
        Return the modified latest messages without embedded files as json strings with at most max_tokens tokens/words and max_file files (at least 1 message even if length > n)

        Fetch data from all input sources whose attention is not none. 
        Combine with existing messages and return the messages as a list and the files
        If a limit is None, then ignore that limit
        """
        # Fetch data from input sources and add it to the current messages list
        new_messages = self.input_sources.fetch()
        self.messages.extend(new_messages)


        # Messages and files to return
        messages = []
        all_file_items = []

        # Get the limits
        max_tokens = self.max_tokens["messages"]
        max_files = self.max_files["messages"]

        current_tokens = 0
        current_files = 0

        # FIXME:  implement the function
        def process_message(message: dict) -> tuple:
            """
            Take a message dict and process it.

            Return the number of tokens and files, the files and the modified message as a string.
            The modified file has only necessary fields and without the files
            """
            # The values to return
            num_tokens = 0
            num_files = 0
            files = []
            new_message = {}

            # Create a deepcopy of the given message
            message = deepcopy(message)

            # If the messsage is an actual message, extract the role and content
            if "role" in message:
                role = message["role"]
                content = message["content"]
                # If it's a user message and content is a list, we process the list to filter out files
                if role == "user" and isinstance(content, list):
                    input_items = [] 
                    for input in content:
                        if input["type"] != "input_text":
                            num_files += 1
                            files.append(input)
                            # Replace the file with an input text that indicates there is a file replaced
                            input_items.append({
                                "type": "input_text",
                                "text": "There was a file here. It has been extracted and included seperately."
                            })
                        else:
                            input_items.append(input)
                    content = input_items

                # Extract the role and content to create a modified message
                new_message = {"role": role, "content": content}
                    
            # If it's a function call output, extract the type, call_id, output
            elif "type" in message and message["type"] == "function_call_output":
                # If it has a list as the output, process the list to extract the files
                if isinstance(message["output"], list):
                    input_items = []
                    for item in message["output"]:
                        # If the current item is a file
                        if item["type"] != "input_text":
                            num_files += 1
                            files.append(item)
                            # Replace the file with an input text that indicates there is a file replaced
                            input_items.append({
                                "type": "input_text",
                                "text": "There was a file here. It has been extracted and included seperately."
                            })
                        else:
                            input_items.append(item)
                    message["output"] = input_items
                # Extract type, call id, output to create a new message
                new_message = {"type": message["type"], "call_id": message["call_id"], "output": input_items}
            # If it's a function call, extract the type, call id, name, arguments
            elif "type" in message and message["type"] == "function_call":
                new_message = {
                    "type": message["type"],
                    "call_id": message["call_id"],
                    "name": message["name"],
                    "arguments": message["arguments"]
                }
            # For other types of messages, don't modify anything
            else:
                new_message = message

            # Convert the new message to a json string and count it
            new_message_str = json.dumps(new_message)
            num_tokens = count(new_message_str)

            return num_tokens, num_files, file_items, new_message_str
            
                
                            
        
        for message in reversed(self.messages):
            num_tokens, num_files, file_items, mod_message = process_message(message)
            current_tokens += num_tokens
            current_files += num_files
            # If there is no message in messages yet, add it anyway
            if len(messages) == 0:
                messages.append(mod_message)
                all_file_items.append(file_items)
                continue

            # If we don't need to execute max tokens limit or current tokens is below it, append the message
            if max_tokens == None or current_tokens <= max_tokens:
                messages.append(mod_message)
            # If num_tokens limit is exceeded, stop adding messages
            else:
                break
            
            # If we don't need to execute max files limit or current number of files is below it, append the files
            if max_files == None or current_files <= max_files:
                all_file_items.extend(file_items)
            # If num_files limit is exceeded, just ignore the files and still add string messages if num_tokens is not exceeded

        # Reverse to get the correct order
        messages = reversed(messages)        
        return messages, all_file_items

    def fetch_context(self) -> dict:
        """
        Combine all the context sections into asingle user message including any files and return it
        """
        messages, file_items = self.fetch_messages()

        # The input text string
        input_text = ""

        # Add the conversation history
        input_text += "History (including your tool calls and reasoning)\n"
        input_text += '\n'.join(messages)

        # The user message to return
        user_message = {
            "role": "user",
            "content": [
                {
                    "type": "input_text",
                    "text": input_text
                }
            ] + file_items
        }

        return user_message
            


    def send_messages(self, messages: list[dict]) -> None:
        """Combine messages from the agent and send them to all output sources that are in use"""
        agent_messages = []

        # Filter to get only messages with the assistant role
        for message in messages:
            if "role" in message and message["role"] == "assistant":
                agent_messages.append(message)
        self.messages.extend(messages)
        self.output_sources.send_messages(agent_messages)
    def send_phrase(self, phrase: str) -> None:
        """Send a phrase to all output sources that are in use for streaming purpose"""
        self.output_sources.send_phrase(phrase)


    # # Wrapper function which provides self parameter to tools and return them
    # # FIXME: implement thought tool which add the tool call to self.messages
    # def list_tools(self):
    #     @function_tool
    #     def think(your_thought: str):
    #         """A tool to think. If you want to think, call this function and give your thought as the argument. Your thoughts are not displayed to others.  Do not output your thought directly"""

    #         self.messages.append({
    #             'role': 'tool',
    #             'content': {
    #                 'time': datetime.now().astimezone(),
    #                 'tool_name': 'think',
    #                 'result': f'You thought: {your_thought}'
    #             }
    #         })
    #         return 'Done'
         
    #     return [think]


    # HELPERS
    # Count the number of words/tokens. Currently words
    def count(self, str):
        return len(str.split(' '))
    
    # Log to log.txt
    def log(self, text):
        with open("log.txt", "a") as f:
            f.write(text+'\n')
    


                
            
