from datetime import datetime, time
import json
from dotenv import load_dotenv
from copy import deepcopy
from memory import MemoryClient, Memory
from sources import InputSource, InputSourceHub, OutputSource, OutputSourceHub, GradioUI
from sql_database.SQLClient import SQLClient, SQLiteClient
from MessageList import MessageList
from prompts import system_prompts
from helpers import count
load_dotenv(override=True)


class Context:
    """
    Contains all the contexts for an agent and their related methods for the agent and input sources to interact with.

    Context:
    - Messages
    - Memory
    - Custom contexts generated by tools, subagents,...

    Input sources:
    - User chat messages fron the chat UI
    - Tool calls, subagents
    """

    # persona_name: str
    # persona: str
    # """
    # Persona configs, loaded from personas.json:
    # persona_name: Name of the persona
    # persona: persona description
    # """

    messages: MessageList
    """History of all messages including tool calls and thoughts"""


    memory_client: MemoryClient
    memories: Memory
    """Memory objects to retrieve memories"""

    sql_client: SQLiteClient
    """SQL Client"""

    input_sources: InputSourceHub
    """Input sources for the agent to fetch input from"""

    output_sources: OutputSourceHub
    """Output sources for the agent to send output to"""


    system_prompt: str
    """System prompt for the agent"""


    max_tokens: dict[str, int]
    """
    The maximum number of tokens in each context sections.
    Each pair consists of section name (messages, memories,...) and max tokens values
    For messages, each summarization will consume half of the limit
    """

    max_files: dict[str, int]
    """
    The maximum number of files in each context sections.
    Each pair consists of section name (messages, memories,...) and max files values
    """



    def __init__(self, input_sources: dict[str, InputSource] = {}, output_sources: dict[str, OutputSource] = {}, agent_name: str = "Alice", agent_type: str = "assistant", max_tokens: int = 5000, max_files: int = 5, summarization_model: str = "qwen3.8-gsq-vision:latest") -> None:
        """
        Init the context

        Get the system prompt from prompts module based on the agent type.
        Init messages (the n latest messages), memory,...

        Parameters:
            input_sources: a dict mapping the source names in str to the InputSource objects
            output_sources: a dict mapping the source names in str to the OutputSource objects
            agent_type: the type of the agent using this Context object
            max_tokens: the maximum number of tokens for the context. Divided into multiple sections in the method
            max_files: the maximum number of files given to the agent
            summarization_model: the model name for the message list to use to summarize
        """
        
        # Initialize input sources
        self.input_sources = InputSourceHub(sources=input_sources)
        self.input_sources.connect_all()

        # Initialize output sources
        self.output_sources = OutputSourceHub(sources=output_sources) 
        self.output_sources.connect_all() 

        
        
    
        # Get the system prompt from prompts module
        self.system_prompt = system_prompts[agent_type]

        self.keywords = {
            # Keyword to indicate there's no new input
            'no_input': '[no input]'
        }

        # Init the context length limit
        # FIXME: add more sections later
        self.max_tokens = {
            "messages": max_tokens
        }
        self.max_files = {
            "messages": max_files
        }

        # Init the sql client
        self.sql_client = SQLiteClient(agent_name=agent_name, agent_type=agent_type, system_message=self.system_prompt)

        # Init the MemoryClient
        self.memory_client = MemoryClient()

        # Init the message list and fetch all messages today
        self.messages = MessageList(self.memory_client, max_tokens=self.max_tokens["messages"], max_files=self.max_files["messages"], agent_name=agent_name, agent_type=agent_type, system_message=self.system_prompt, summarization_model=summarization_model)

        

        

    async def async_init(self):
        """
        Do all inits process that require to be async
        """
        # Add the today message to message list
        time_now = datetime.now()
        start_time_today = time_now.combine(time_now.date(), time.min)
        seconds_ago = (datetime.now() - start_time_today).total_seconds()
        today_messages = self.sql_client.get_messages(seconds_ago)
        await self.messages.add_messages(today_messages, save=False)

    async def fetch_context(self) -> list:
        """
        Combine all the context sections into a single user message including any files and return it
        """
        # Get new messages from input sources and add them to the message list
        new_messages = self.input_sources.fetch()
        await self.messages.add_messages(new_messages)
        summary = self.messages.summary
        messages = self.messages.modified_messages
        files = self.messages.files_modified_messages

        # The input text string
        input_text = f"Summary of events before history:\n{summary}\n"

        # Add the conversation history
        input_text += "Below is the history. Note that all assistant messages are the messages you send to the user while the tool call and results are invisible to the user\n"
        input_text += '\n'.join(messages)

        # The user message to return
        user_message = {
            "role": "user",
            "content": [
                {
                    "type": "input_text",
                    "text": input_text
                }
            ] + files
        }

        return [user_message]
            


    async def send_messages(self, messages: list[dict]) -> None:
        """Combine messages from the agent and send them to all output sources that are in use"""
        agent_messages = []

        # Filter to get only messages with the assistant role
        for message in messages:
            if "role" in message and message["role"] == "assistant":
                agent_messages.append(message)
        self.output_sources.send_messages(agent_messages)

        # Add the messages to the original messages list
        await self.messages.add_messages(messages)
    def send_phrase(self, phrase: str) -> None:
        """Send a phrase to all output sources that are in use for streaming purpose"""
        self.output_sources.send_phrase(phrase)


    # # Wrapper function which provides self parameter to tools and return them
    # # FIXME: implement thought tool which add the tool call to self.messages
    # def list_tools(self):
    #     @function_tool
    #     def think(your_thought: str):
    #         """A tool to think. If you want to think, call this function and give your thought as the argument. Your thoughts are not displayed to others.  Do not output your thought directly"""

    #         self.messages.append({
    #             'role': 'tool',
    #             'content': {
    #                 'time': datetime.now().astimezone(),
    #                 'tool_name': 'think',
    #                 'result': f'You thought: {your_thought}'
    #             }
    #         })
    #         return 'Done'
         
    #     return [think]


    


                
            
