from datetime import datetime
import json
from dotenv import load_dotenv
from memory import MemoryClient, Memory
from sources import InputSource, InputSourceHub, OutputSource, OutputSourceHub, GradioUI
load_dotenv(override=True)


class Context:
    """
    Contains all the contexts for an agent and their related methods for the agent and input sources to interact with.

    Context:
    - Messages
    - Memory
    - Custom contexts generated by tools, subagents,...

    Input sources:
    - User chat messages fron the chat UI
    - Tool calls, subagents
    """

    # persona_name: str
    # persona: str
    # """
    # Persona configs, loaded from personas.json:
    # persona_name: Name of the persona
    # persona: persona description
    # """

    messages = []
    """History of all messages including tool calls and thoughts"""


    # memory_client: MemoryClient
    # memories: Memory
    # """Memory objects to retrieve memories"""

    input_sources: InputSourceHub
    """Input sources for the agent to fetch input from"""

    output_sources: OutputSourceHub
    """Output sources for the agent to send output to"""

    reasoning_prompt: str
    """The latest user message sent to the reasoning_agent. Used to remind the agent in a single long run"""

    system_prompt: str
    """System prompt for the agent"""
    keywords: dict
    """Special keywords in prompts that need care"""


    def __init__(self, input_sources: dict[str, InputSource] = {}, output_sources: dict[str, OutputSource] = {}, system_prompt: str = "") -> None:
        
        # Initialize input sources
        self.input_sources = InputSourceHub(sources=input_sources)
        self.input_sources.connect_all()

        # Initialize output sources
        self.output_sources = OutputSourceHub(sources=output_sources) 
        self.output_sources.connect_all() 

        

        self.messages = [{
            'role': 'user',
            'content': f'System starts. Now is {datetime.now().astimezone().isoformat()}'
            }]
        self.simple_conversation_history = ''

        self.reasoning_prompt = ''
        self.system_prompt = system_prompt

        self.keywords = {
            # Keyword to indicate there's no new input
            'no_input': '[no input]'
        }

    def fetch(self) -> list[dict]:
        """Fetch data from all input sources whose attention is not none. Combine with existing messages and return all"""
        new_messages = self.input_sources.fetch()
        self.messages.extend(new_messages)
        messages = self.messages.copy()
        return messages

    def send_messages(self, messages: list[dict]) -> None:
        """Combine messages from the agent and send them to all output sources that are in use"""
        agent_messages = []

        # Filter to get only messages with the assistant role
        for message in messages:
            if "role" in message and message["role"] == "assistant":
                agent_messages.append(message)
        self.messages.extend(messages)
        self.output_sources.send_messages(agent_messages)
    def send_phrase(self, phrase: str) -> None:
        """Send a phrase to all output sources that are in use for streaming purpose"""
        self.output_sources.send_phrase(phrase)


    # # Wrapper function which provides self parameter to tools and return them
    # # FIXME: implement thought tool which add the tool call to self.messages
    # def list_tools(self):
    #     @function_tool
    #     def think(your_thought: str):
    #         """A tool to think. If you want to think, call this function and give your thought as the argument. Your thoughts are not displayed to others.  Do not output your thought directly"""

    #         self.messages.append({
    #             'role': 'tool',
    #             'content': {
    #                 'time': datetime.now().astimezone(),
    #                 'tool_name': 'think',
    #                 'result': f'You thought: {your_thought}'
    #             }
    #         })
    #         return 'Done'
         
    #     return [think]


    # HELPERS
    # Count the number of words/tokens. Currently words
    def count(self, str):
        return len(str.split(' '))
    
    # Log to log.txt
    def log(self, text):
        with open("log.txt", "a") as f:
            f.write(text+'\n')
    


                
            
